In [1]:
with open("/mnt/d/forCoding_code/_init_tools/x__params.py", "r") as f:
    txt = f.read()
exec(txt)

with open("/mnt/d/forCoding_code/_init_tools/report_macro_0516.py", "r") as f:
    txt = f.read()
exec(txt)

with open("/mnt/d/forCoding_code/_init_tools/x__tool_here1.py", "r") as f:
    exec(f.read())
with open("/mnt/d/forCoding_code/_init_tools/x__tool_here2.py", "r") as f:
    exec(f.read())

wasted_dir = "./wasted"
if not os.path.exists(wasted_dir):
    os.makedirs(wasted_dir)

pd.set_option('display.max_rows',200)
pd.set_option('display.max_columns',200)

storage dir: /mnt/d/forCoding_data/QuantFinance/plan_1-select_stock_by_week
code dir: /mnt/d/forCoding_code/QuantFinance/plan_1-select_stock_by_week

In [8]:
!python try_api-baostock.py

login success!
系统登录成功: success
开始获取股票列表...
成功获取 8628 条股票记录
文件已保存至: /mnt/d/forCoding_code/QuantFinance/plan_1-select_stock_by_week/all_stock_list.csv
logout success!
系统已登出

In [16]:
!python bao_get_single_stock.py

正在读取股票列表: /mnt/d/forCoding_code/QuantFinance/plan_1-select_stock_by_week/all_stock_list.csv
计划下载 5509 只股票的数据，使用 6 个进程并发
下载进度:   0%|                                        | 0/5509 [00:00<?, ?it/s]login success!
login success!
login success!
下载进度:   0%|                              | 1/5509 [00:01<2:37:29,  1.72s/it]login success!
下载进度:   0%|                                | 6/5509 [00:04<41:14,  2.22it/s]login success!
下载进度:   0%|                              | 7/5509 [00:05<1:04:50,  1.41it/s]login success!
下载进度: 100%|█████████████████████████████| 5509/5509 [46:33<00:00,  1.97it/s]
所有任务完成。
已登出 baostock

In [8]:
df_k = pd.read_csv("/mnt/d/forCoding_data/QuantFinance/plan_1-select_stock_by_week/originalData/sh.600004.csv")

In [9]:
df_k

,date,code,open,high,low,close,volume,amount,adjustflag,turn,pctChg
0,2003-04-30,sh.600004,3.422152,4.033884,3.408854,3.927496,342805345,2.858185e+09,2,85.701336,50.680272
1,2003-05-16,sh.600004,3.856571,3.931929,3.510809,3.794511,170036504,1.431987e+09,2,42.509126,-3.386005
2,2003-05-23,sh.600004,3.812242,4.220064,3.767914,4.042750,159405597,1.425895e+09,2,39.851399,6.542056
3,2003-05-30,sh.600004,4.033884,4.224497,3.971825,4.091511,149126634,1.373168e+09,2,37.281659,1.206140
4,2003-06-06,sh.600004,4.100377,4.197899,4.020586,4.060481,68870489,6.363894e+08,2,17.217622,-0.758397
...,...,...,...,...,...,...,...,...,...,...,...
1156,2026-01-23,sh.600004,9.350000,9.710000,9.350000,9.650000,108118395,1.033980e+09,2,4.568300,2.988300
1157,2026-01-30,sh.600004,9.620000,9.670000,9.480000,9.560000,95385323,9.113334e+08,2,4.030400,-0.932600
1158,2026-02-06,sh.600004,9.570000,9.690000,9.350000,9.510000,143177549,1.367805e+09,2,6.049700,-0.523000
1159,2026-02-13,sh.600004,9.550000,9.560000,9.360000,9.370000,76783761,7.279835e+08,2,3.244400,-1.472100
1160,2026-02-27,sh.600004,9.400000,9.460000,9.370000,9.400000,51427758,4.837546e+08,2,2.172900,0.320200

In [2]:
!ls /mnt/d/forCoding_data/QuantFinance/plan_1-select_stock_by_week

originalData  preprocessedData	trained_models

In [3]:
create_originalData_path("")

'/mnt/d/forCoding_data/QuantFinance/plan_1-select_stock_by_week/originalData/'

In [9]:
df_stk_list = pd.read_csv("all_stock_list.csv")

In [21]:
df_stk_list[
    df_stk_list.outDate.isnull() #& (~df_stk_list.code_name.str.contains("指数|上证|深证"))
]

           code   code_name     ipoDate outDate  type  status
0     sh.000001      上证综合指数  1991-07-15     NaN     2       1
1     sh.000002      上证A股指数  1992-02-21     NaN     2       1
2     sh.000003      上证B股指数  1992-08-17     NaN     2       1
3     sh.000004     上证工业类指数  1993-05-03     NaN     2       1
4     sh.000005     上证商业类指数  1993-05-03     NaN     2       1
...         ...         ...         ...     ...   ...     ...
8623  sz.399994  中证信息安全主题指数  2015-03-12     NaN     2       1
8624  sz.399995    中证基建工程指数  2015-03-12     NaN     2       1
8625  sz.399996    中证智能家居指数  2014-09-17     NaN     2       1
8626  sz.399997      中证白酒指数  2015-01-21     NaN     2       1
8627  sz.399998      中证煤炭指数  2015-02-13     NaN     2       1

[7567 rows x 6 columns]

In [22]:
df_stk_list.status.value_counts()

status
1    7567
0    1061
Name: count, dtype: int64

In [2]:
import akshare as ak
stock_code = "600519"
df = ak.stock_zh_a_hist(symbol=stock_code, period="daily")
df = df.rename(columns={
    '日期': 'date', '开盘': 'open', '收盘': 'close', '最高': 'high', '最低': 'low',
    '成交量': 'volume', '成交额': 'amount', '涨跌幅': 'pct_chg', '换手率': 'turnover_rate'
})

In [3]:
df

,date,股票代码,open,close,high,low,volume,amount,振幅,pct_chg,涨跌额,turnover_rate
0,2001-08-27,600519,34.51,35.55,37.78,32.85,406318,1.410347e+09,15.71,13.25,4.16,56.83
1,2001-08-28,600519,34.99,36.86,37.00,34.61,129647,4.634630e+08,6.72,3.68,1.31,18.13
2,2001-08-29,600519,36.98,36.38,37.00,36.10,53252,1.946890e+08,2.44,-1.30,-0.48,7.45
3,2001-08-30,600519,36.28,37.10,37.51,36.00,48013,1.775580e+08,4.15,1.98,0.72,6.72
4,2001-08-31,600519,37.15,37.01,37.62,36.80,23231,8.623100e+07,2.21,-0.24,-0.09,3.25
...,...,...,...,...,...,...,...,...,...,...,...,...
5863,2026-02-13,600519,1486.60,1485.30,1507.80,1470.58,41679,6.216379e+09,2.50,-0.09,-1.30,0.33
5864,2026-02-24,600519,1521.00,1466.80,1524.40,1463.60,41913,6.198841e+09,4.09,-1.25,-18.50,0.33
5865,2026-02-25,600519,1470.00,1491.66,1509.66,1467.88,36881,5.490316e+09,2.85,1.69,24.86,0.29
5866,2026-02-26,600519,1486.60,1466.21,1489.49,1464.67,32958,4.855471e+09,1.66,-1.71,-25.45,0.26
5867,2026-02-27,600519,1466.99,1455.02,1476.21,1455.02,32160,4.697692e+09,1.45,-0.76,-11.19,0.26

In [6]:
df = ak.stock_zh_a_hist(symbol=stock_code, period="daily")

ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

In [4]:
df = ak.stock_zh_a_hist(symbol=stock_code, period="weekly")

ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

In [5]:
stock_new_a_spot_em_df = ak.stock_new_a_spot_em()
print(stock_new_a_spot_em_df)

ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

In [6]:
!pip install baostock

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/
Collecting baostock
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/b2/37/bbabac2d33723d71bd8dbd5e819d9cbe5dc1e031b7dd12ed7de8fa040816/baostock-0.8.9-py3-none-any.whl (45 kB)
Requirement already satisfied: pandas>=0.18.0 in /home/xiuminke/miniconda3/envs/ml12/lib/python3.11/site-packages (from baostock) (2.3.3)
Requirement already satisfied: numpy>=1.23.2 in /home/xiuminke/miniconda3/envs/ml12/lib/python3.11/site-packages (from pandas>=0.18.0->baostock) (1.25.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/xiuminke/miniconda3/envs/ml12/lib/python3.11/site-packages (from pandas>=0.18.0->baostock) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/xiuminke/miniconda3/envs/ml12/lib/python3.11/site-packages (from pandas>=0.18.0->baostock) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/xiuminke/miniconda3/envs/ml12/lib/python3.11/site-packages (from pandas>=0.18.0->baostock) (2025.2)
Requirement already satisfied: six>=1.5 in /home/xiuminke/miniconda3/envs/ml12/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=0.18.0->baostock) (1.17.0)
Installing collected packages: baostock
Successfully installed baostock-0.8.9

In [7]:
import baostock as bs
import pandas as pd

#### 登陆系统 ####
lg = bs.login()
# 显示登陆返回信息
print('login respond error_code:'+lg.error_code)
print('login respond  error_msg:'+lg.error_msg)

#### 获取沪深A股历史K线数据 ####
# 详细指标参数，参见“历史行情指标参数”章节；“分钟线”参数与“日线”参数不同。“分钟线”不包含指数。
# 分钟线指标：date,time,code,open,high,low,close,volume,amount,adjustflag
# 周月线指标：date,code,open,high,low,close,volume,amount,adjustflag,turn,pctChg
rs = bs.query_history_k_data_plus("sh.600000",
    "date,time,code,open,high,low,close,volume,amount,adjustflag",
    start_date='2024-07-01', end_date='2024-12-31',
    frequency="5", adjustflag="3")
print('query_history_k_data_plus respond error_code:'+rs.error_code)
print('query_history_k_data_plus respond  error_msg:'+rs.error_msg)

#### 打印结果集 ####
data_list = []
while (rs.error_code == '0') & rs.next():
    # 获取一条记录，将记录合并在一起
    data_list.append(rs.get_row_data())
result = pd.DataFrame(data_list, columns=rs.fields)

#### 结果集输出到csv文件 ####   
result.to_csv("history_A_stock_k_data.csv", index=False)
print(result)

#### 登出系统 ####
bs.logout()

login success!
login respond error_code:0
login respond  error_msg:success
query_history_k_data_plus respond error_code:0
query_history_k_data_plus respond  error_msg:success
            date               time       code     open     high      low  \
0     2024-07-01  20240701093500000  sh.600000   8.2200   8.2600   8.2100
1     2024-07-01  20240701094000000  sh.600000   8.2400   8.2400   8.2200
2     2024-07-01  20240701094500000  sh.600000   8.2400   8.2500   8.2300
3     2024-07-01  20240701095000000  sh.600000   8.2300   8.2400   8.2300
4     2024-07-01  20240701095500000  sh.600000   8.2300   8.2600   8.2300
...          ...                ...        ...      ...      ...      ...
5995  2024-12-31  20241231144000000  sh.600000  10.3300  10.3500  10.3200
5996  2024-12-31  20241231144500000  sh.600000  10.3300  10.3600  10.3200
5997  2024-12-31  20241231145000000  sh.600000  10.3600  10.3700  10.3200
5998  2024-12-31  20241231145500000  sh.600000  10.3300  10.3300  10.3000
5999  2024-12-31  20241231150000000  sh.600000  10.3100  10.3100  10.2900

        close   volume         amount adjustflag
0      8.2300  1396900  11516198.0000          3
1      8.2400   552800   4551811.0000          3
2      8.2400   637000   5247083.0000          3
3      8.2300   526000   4331764.0000          3
4      8.2500   872200   7194432.0000          3
...       ...      ...            ...        ...
5995  10.3300  1520700  15718720.0000          3
5996  10.3600  2468700  25508256.0000          3
5997  10.3300  1670700  17285600.0000          3
5998  10.3100  2822800  29113915.0000          3
5999  10.2900  2855700  29389309.0000          3

[6000 rows x 10 columns]
logout success!

In [25]:
# time.sleep(10)

In [ ]:
for

In [7]:
!python get_weekly_data.py

正在获取A股股票列表...
尝试获取股票列表 (第 1 次)...
尝试1 (stock_zh_a_spot_em) 失败: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
尝试备选接口 (stock_info_a_code_name)...
共获取到 5484 只股票。
开始下载周度数据 (Weekly Data)...
Downloading:   0%|                                  | 0/5484 [00:00<?, ?stock/s]下载 000001 失败，已达到最大重试次数。错误: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Downloading:   0%|    | 1/5484 [00:20<31:00:44, 20.36s/stock, Success=0, Fail=1]下载 000002 失败，已达到最大重试次数。错误: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Downloading:   0%|    | 2/5484 [00:40<30:53:56, 20.29s/stock, Success=0, Fail=2]下载 000004 失败，已达到最大重试次数。错误: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Downloading:   0%|    | 3/5484 [01:01<31:04:47, 20.41s/stock, Success=0, Fail=3]下载 000006 失败，已达到最大重试次数。错误: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Downloading:   0%|    | 4/5484 [01:23<31:59:32, 21.02s/stock, Success=0, Fail=4]下载 000007 失败，已达到最大重试次数。错误: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Downloading:   0%|    | 5/5484 [01:43<31:53:40, 20.96s/stock, Success=0, Fail=5]^C
Downloading:   0%|    | 5/5484 [02:02<37:17:24, 24.50s/stock, Success=0, Fail=5]
Traceback (most recent call last):
  File "/home/xiuminke/miniconda3/envs/ml12/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/xiuminke/miniconda3/envs/ml12/lib/python3.11/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/xiuminke/miniconda3/envs/ml12/lib/python3.11/site-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiuminke/miniconda3/envs/ml12/lib/python3.11/http/client.py", line 1395, in getresponse
    response.begin()
  File "/home/xiuminke/miniconda3/envs/ml12/lib/python3.11/http/client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/home/xiuminke/miniconda3/envs/ml12/lib/python3.11/http/client.py", line 294, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xiuminke/miniconda3/envs/ml12/lib/python3.11/site-packages/requests/adapters.py", line 644, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/xiuminke/miniconda3/envs/ml12/lib/python3.11/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/xiuminke/miniconda3/envs/ml12/lib/python3.11/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiuminke/miniconda3/envs/ml12/lib/python3.11/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/xiuminke/miniconda3/envs/ml12/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/xiuminke/miniconda3/envs/ml12/lib/python3.11/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/xiuminke/miniconda3/envs/ml12/lib/python3.11/site-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiuminke/miniconda3/envs/ml12/lib/python3.11/http/client.py", line 1395, in getresponse
    response.begin()
  File "/home/xiuminke/miniconda3/envs/ml12/lib/python3.11/http/client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/home/xiuminke/miniconda3/envs/ml12/lib/python3.11/http/client.py", line 294, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/d/forCoding_code/QuantFinance/plan_1-select_stock_by_week/get_weekly_data.py", line 61, in download_stock_data
    df = ak.stock_zh_a_hist(symbol=symbol, period=period, adjust="qfq")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiuminke/miniconda3/envs/ml12/lib/python3.11/site-packages/akshare/stock_feature/stock_hist_em.py", line 992, in stock_zh_a_hist
    r = requests.get(url, params=params, timeout=timeout)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiuminke/miniconda3/envs/ml12/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiuminke/miniconda3/envs/ml12/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiuminke/miniconda3/envs/ml12/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiuminke/miniconda3/envs/ml12/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiuminke/miniconda3/envs/ml12/lib/python3.11/site-packages/requests/adapters.py", line 659, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/d/forCoding_code/QuantFinance/plan_1-select_stock_by_week/get_weekly_data.py", line 155, in <module>
    main()
  File "/mnt/d/forCoding_code/QuantFinance/plan_1-select_stock_by_week/get_weekly_data.py", line 132, in main
    df = download_stock_data(symbol, period='weekly')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/forCoding_code/QuantFinance/plan_1-select_stock_by_week/get_weekly_data.py", line 83, in download_stock_data
    time.sleep(wait_time)
KeyboardInterrupt